# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import value.deliverables.models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decisionitem',
            options={'verbose_name': 'decision item', 'verbose_name_plural': 'decision items'},
        ),
        migrations.AlterModelOptions(
            name='decisionitemattachment',
            options={'verbose_name': 'attachment', 'verbose_name_plural': 'attachments'},
        ),
        migrations.AlterModelOptions(
            name='decisionitemlookup',
            options={'verbose_name': 'decision items lookup', 'verbose_name_plural': 'decision items lookups'},
        ),
        migrations.AlterModelOptions(
            name='deliverable',
            options={'verbose_name': 'deliverable', 'verbose_name_plural': 'deliverables'},
        ),
        migrations.AlterField(
            model_name='decisionitem',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='decisionitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='decisionitemattachment',
            name='attachment',
            field=models.FileField(upload_to=value.deliverables.models.attachment_file_upload_to, verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='decisionitemlookup',
            name='column_display',
            field=models.BooleanField(default=True, verbose_name='column display'),
        ),
        migrations.AlterField(
            model_name='decisionitemlookup',
            name='column_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='column label'),
        ),
        migrations.AlterField(
            model_name='decisionitemlookup',
            name='column_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='column name'),
        ),
        migrations.AlterField(
            model_name='decisionitemlookup',
            name='column_type',
            field=models.CharField(choices=[(b'S', 'String'), (b'F', 'Float'), (b'I', 'Integer'), (b'D', 'Date'), (b'T', 'Date Time')], default=b'S', max_length=1, verbose_name='column type'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
