# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-29 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0002_auto_20160326_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionitem',
            name='is_managed',
            field=models.BooleanField(default=False),
        ),
    ]
