# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-11-14 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliverables', '0003_decisionitem_is_managed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='admins',
            field=models.ManyToManyField(related_name='_deliverable_admins_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
