# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-02-13 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0004_deliverable_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
