# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0002_auto_20151014_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factor',
            options={'ordering': ('group', 'name'), 'verbose_name': 'value factor', 'verbose_name_plural': 'value factors'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'value factors group', 'verbose_name_plural': 'value factors groups'},
        ),
        migrations.AlterField(
            model_name='factor',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factors.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
