# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-24 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0003_auto_20160325_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
