# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160325_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
