# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20160321_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingitem',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting'),
        ),
        migrations.AlterField(
            model_name='meetingstakeholder',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting'),
        ),
    ]
