# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_auto_20160321_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
