# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 16:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_meetingitem_has_rationales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluation',
            options={'verbose_name': 'evaluation', 'verbose_name_plural': 'evaluations'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-updated_at',), 'verbose_name': 'meeting', 'verbose_name_plural': 'meetings'},
        ),
        migrations.AlterModelOptions(
            name='meetingitem',
            options={'ordering': ('decision_item__name',), 'verbose_name': 'meeting item', 'verbose_name_plural': 'meeting items'},
        ),
        migrations.AlterModelOptions(
            name='rationale',
            options={'verbose_name': 'rationale', 'verbose_name_plural': 'rationales'},
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='evaluated at'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'created at'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings_created', to=settings.AUTH_USER_MODEL, verbose_name=b'created by'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name=b'description'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'ended at'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'location'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=255, verbose_name=b'name'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='progress',
            field=models.FloatField(default=0.0, verbose_name='progress'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='rationales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='rationales count'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='started_at',
            field=models.DateTimeField(verbose_name=b'started at'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[(b'O', 'Ongoing'), (b'A', 'Analysing'), (b'C', 'Closed')], default=b'O', max_length=1, verbose_name=b'status'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meetings_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='has_rationales',
            field=models.BooleanField(default=False, verbose_name='has rationales?'),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='meeting_decision',
            field=models.BooleanField(default=False, verbose_name='meeting decision'),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='meeting_ranking',
            field=models.FloatField(default=0.0, verbose_name='meeting ranking'),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='value_ranking',
            field=models.FloatField(default=0.0, verbose_name='value ranking'),
        ),
        migrations.AlterField(
            model_name='meetingstakeholder',
            name='meeting_input',
            field=models.FloatField(default=0.0, verbose_name='meeting input'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='percentage_votes',
            field=models.FloatField(default=0.0, verbose_name='percentage votes'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='raw_votes',
            field=models.IntegerField(default=0, verbose_name='raw votes'),
        ),
        migrations.AlterField(
            model_name='rationale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='rationale',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rationales_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='rationale',
            name='text',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='rationale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='rationale',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rationales_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='value_ranking',
            field=models.FloatField(default=0.0, verbose_name='value ranking'),
        ),
    ]
