# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_auto_20160328_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingitem',
            name='meeting_decision_rationale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_decision_meeting_items', to='meetings.Rationale'),
        ),
    ]
