# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_meetingitem_meeting_decision_rationale'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_decision_rationale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_decision_meetings', to='meetings.Rationale'),
        ),
    ]
