# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-28 15:49
from __future__ import unicode_literals

import uuid

from django.db import migrations


def create_uuid(apps, schema_editor):
    Meeting = apps.get_model('meetings', 'Meeting')
    for meeting in Meeting.objects.all():
        meeting.survey_id = uuid.uuid4()
        meeting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0013_auto_20171128_1546'),
    ]

    operations = [
        migrations.RunPython(create_uuid),
    ]
