# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0015_auto_20171128_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingstakeholder',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
