# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-07 14:42
from __future__ import unicode_literals

from django.db import migrations

def update_meeting_input(apps, schema_editor):
    MeetingStakeholder = apps.get_model('meetings', 'MeetingStakeholder')
    Evaluation = apps.get_model('meetings', 'Evaluation')

    for ms in MeetingStakeholder.objects.all():
        evaluations_count = Evaluation.objects.filter(
            meeting=ms.meeting,
            factor__in=ms.meeting.factors.all(),
            measure=ms.meeting.measure,
            user=ms.stakeholder
        ).exclude(measure_value=None).count()
        factors_count = ms.meeting.factors.count()
        meeting_items_count = ms.meeting.meetingitem_set.count()
        max_input = factors_count * meeting_items_count

        percentage = 0.0
        if max_input != 0:
            percentage = (evaluations_count / float(max_input)) * 100.0
            percentage = round(percentage, 2)

        ms.meeting_input = percentage
        ms.save()


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0016_meetingstakeholder_is_external'),
    ]

    operations = [
        migrations.RunPython(update_meeting_input),
    ]
