# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-11-20 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0017_auto_20180307_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='meeting_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingItem'),
        ),
    ]
