# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-11-20 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0018_auto_20181120_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingitem',
            name='decision_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.DecisionItem'),
        ),
    ]
