# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-02-11 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0020_remove_duplicate_stakeholders'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingstakeholder',
            unique_together=set([('meeting', 'stakeholder')]),
        ),
    ]
